site_name: rvx!
site_url: https://mxjp.github.io/rvx
theme:
  name: material
  logo: assets/logo.svg
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - toc.integrate
    - content.tabs.link
  palette:
    scheme: slate
    primary: black
    accent: blue

extra:
  generator: false

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

repo_url: https://github.com/mxjp/rvx
