name: GitHub Pages

on:
  push:
    branches: main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
      - run: python -m pip install -r docs/requirements.txt
      # TODO: Build & publish:
      # - uses: actions/upload-pages-artifact@v2
      #   with:
      #     path: './docs/dist'
      # - uses: actions/deploy-pages@v2
      #   id: deployment
